<h1>内部関数が例外を投げるようにする</h1>

<p>set_error_handler()を利用する。</p>

<h3>set_error_handler()のサンプル</h3>

<pre><code class="php">&lt;?php
function exceptionErrorHandler($errno, $errstr, $errfile, $errline) {
   throw new ErrorException($errstr, 0, $errno, $errfile, $errline);
}
set_error_handler('exceptionErrorHandler');
</code></pre>

<h3>例外発生を確認</h3>

<pre><code class="php">&lt;?php
error_reporting(E_ALL);
try {
   $arr = array();
   print $arr['a'] . "\n";
   strpos();
} catch (Exception $e) {
   print $e-&gt;getMessage() . "\n";
   print $e-&gt;getTraceAsString() . "\n";
}
</code></pre>
